{% set name = "conda-package-handling" %}
{% set version = "2.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/conda/conda-package-handling/archive/{{ version }}.tar.gz
  sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - cph = conda_package_handling.cli:main
  noarch: python

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python >=3.7
    - pip
    - wheel
  run:
    - python >=3.7
    - python
    - conda-package-streaming >=0.7.0

test:
  source_files:
    - tests
  requires:
    - mock
    - pytest
    - pytest-cov
    - pytest-mock
  imports:
    - conda_package_handling
    - conda_package_handling.api
  commands:
    - pytest -v --cov=conda_package_handling --color=yes tests/

about:
  home: https://github.com/conda/conda-package-handling
  dev_url: https://github.com/conda/conda-package-handling
  doc_url: https://conda.github.io/conda-package-handling/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  summary: Create and extract conda packages of various formats

extra:
  recipe-maintainers:
    - beckermr
    - dbast
    - dholth
    - jezdez
    - msarahan
