{% set name = "conda-package-handling-build" %}
{% set version = "1.7.0" %}

{% set libarchive_version = "3.3.3" %}
# 3.4.0 breaks some symlink stuff on macos.  Holding back for now.

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/conda/conda-package-handling/archive/{{ version }}.tar.gz
    sha256: 56fba119552f1796df5bdd21fa11c03cc2b2fcd489d1cfb2f57ad9c8d7ed9c88
    folder: cph

  - url: https://github.com/libarchive/libarchive/releases/download/v{{ libarchive_version }}/libarchive-{{ libarchive_version }}.tar.gz
    sha256: ba7eb1781c9fbbae178c4c6bad1c6eb08edab9a1496c64833d1715d022b30e2e
    patches:
      - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
      - patches/0002-xar-fix-bad-seek-in-move_reading_point.patch
      - patches/0003-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
      - patches/0004-VC9-compatibility-define-BCRYPT_SUCCESS.patch
      # This should not be applied in general. It exists so I can build it for
      # debugging Visual Studio where warnings are errors for some reason.
      # Hiding warnings is poor practice.
      # - patches/0005-VC9-compatibility-ignore-some-warnings.patch
      - patches/0006-VC-openssl-define-inline-as-__inline.patch
      # These warnings are errors when compiling lz-4 support
      - patches/0007-CMake-VC9-compatibility-ignore-some-warnings.patch
      - patches/0008-VC9-compatibility-remove-C99.patch
      - patches/0009-CMake-Force-Multi-threaded-DLL-runtime.patch
      # 3.4.0 added official support for symlinks on win
      - patches/0010-Use-CreateSymbolicLinkW-on-Windows-for-symlinks-WIP.patch
    folder: libarchive

build:
  number: 4

outputs:
  # Recipe for a static libarchive with support for the features needed for
  # conda-package-handling (bzip2, zlib, zstd).
  # This is not a general purpose libarchive
  - name: _libarchive_static_for_cph
    version: {{ libarchive_version }}
    script: build-libarchive.sh  # [unix]
    script: bld-libarchive.bat  # [win]
    build:
      ignore_run_exports:
        - bzip2
        - libiconv
        - zlib
        - zstd
      # HACK: case-sensitive mismatch in latest conda-build
      missing_dso_whitelist:
        - Library/bin/VCRUNTIME140.dll    # [win]
        - "*/MSVCR90.dll"                 # [win]
        - "MSVCR90.dll"                   # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        # Does not work in this recips at present
        # we manually convert C99 to C89 instead.
        # - c99-to-c89  # [win and vc<14]
        - msinttypes  # [win and vc<14]
        - autoconf    # [unix]
        - automake    # [unix]
        - libtool     # [unix]
        - pkg-config  # [unix]
        - cmake       # [win]
        - make        # [unix]
        - m2-patch    # [win]
      host:
        - msinttypes  # [win and vc<14]
        - bzip2
        - libiconv    # [osx]
        - zlib
        - zstd-static  # [unix]
        - zstd         # [win]

    test:
      commands:
        # Verify headers are in place.
        - test -f "${PREFIX}/include/archive.h"                              # [unix]
        - test -f "${PREFIX}/include/archive_entry.h"                        # [unix]
        - if not exist %PREFIX%\Library\include\archive.h exit /b 1         # [win]
        - if not exist %PREFIX%\Library\include\archive_entry.h exit /b 1   # [win]

        # Verify libraries are in place.
        - test -f "${PREFIX}/lib/libarchive.a"                               # [unix]
        - test -f "${PREFIX}/lib/libarchive_and_deps.a"                      # [unix]
        - if not exist %PREFIX%\Library\lib\archive_static.lib exit /b 1    # [win]
        - if not exist %PREFIX%\Library\lib\archive_and_deps.lib exit /b 1  # [win]

    about:
      home: http://www.libarchive.org/
      summary: a static build of libarchive containing only conda-related parts
      license: BSD-2-Clause
      license_file:
        - static_deps_licenses/bzip2.txt
        - static_deps_licenses/libarchive.txt
        - static_deps_licenses/zlib.txt
        - static_deps_licenses/zstd.txt
        - static_deps_licenses/msinttypes.txt  # [win and py27]
        - static_deps_licenses/libiconv.txt    # [osx]


  - name: conda-package-handling
    version: {{ version }}
    script: build-cph.sh
    build:
      entry_points:
        - cph = conda_package_handling.cli:main
      # HACK: case-sensitive mismatch in latest conda-build
      missing_dso_whitelist:
        - "*/VCRUNTIME140.dll"   # [win]
        - "MSVCR90.dll"   # [win]
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - python
        - pip
        - cython
        - {{ pin_subpackage('_libarchive_static_for_cph', exact=True) }}
        - msinttypes  # [win and vc<14]
      run:
        - futures   # [py27]
        - python
        - six
        - tqdm

    test:
      source_files:
        - cph/tests
      requires:
        - mock
        - pytest
        - pytest-cov
        - pytest-mock
      imports:
        - conda_package_handling
        - conda_package_handling.archive_utils_cy
      commands:
        # This test is skipped until Dec 2019 which is weird. Skip for now.
        - pytest cph/tests -k "not test_secure_refusal_to_extract_abs_paths"

    about:
      home: https://github.com/conda/conda-package-handling
      license: BSD-3-Clause
      license_family: BSD
      license_file:
        - cph/LICENSE
        - static_deps_licenses/bzip2.txt
        - static_deps_licenses/libarchive.txt
        - static_deps_licenses/zlib.txt
        - static_deps_licenses/zstd.txt
        - static_deps_licenses/msinttypes.txt  # [win and py27]
        - static_deps_licenses/libiconv.txt    # [osx]
      summary: Create and extract conda packages of various formats

about:
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_file:
    - cph/LICENSE
    - static_deps_licenses/bzip2.txt
    - static_deps_licenses/libarchive.txt
    - static_deps_licenses/zlib.txt
    - static_deps_licenses/zstd.txt
    - static_deps_licenses/msinttypes.txt  # [win and py27]
    - static_deps_licenses/libiconv.txt    # [osx]
  summary: Create and extract conda packages of various formats

extra:
  recipe-maintainers:
    - jjhelmus
    - msarahan
